import React,{useState} from 'react';
import {SafeAreaView,View,Text,TextInput,TouchableOpacity,StyleSheet} from 'react-native';

export default function App(){
 const [user,setUser]=useState(''); const [pass,setPass]=useState(''); const [error,setError]=useState(''); const [logged,setLogged]=useState(false);
 const login=()=>{if(user.trim().toLowerCase()==='ambulance'&&pass==='ambulance123'){setError('');setLogged(true)}else setError('Invalid ambulance credentials.');};
 if(logged)return <SafeAreaView style={s.shell}><View style={s.card}><Text style={s.logo}>R</Text><Text style={s.title}>Ambulance App</Text><Text style={s.ok}>Signed in as AMB-17</Text><Text style={s.body}>Emergency dispatch, live GPS, hospital matching and dynamic referral are ready.</Text><TouchableOpacity style={s.btn} onPress={()=>setLogged(false)}><Text style={s.btnText}>Log out</Text></TouchableOpacity></View></SafeAreaView>;
 return <SafeAreaView style={s.shell}><View style={s.card}><Text style={s.logo}>R</Text><Text style={s.title}>ResQFlow</Text><Text style={s.sub}>Ambulance App Login</Text><Text style={s.label}>Username</Text><TextInput style={s.input} value={user} onChangeText={setUser} placeholder="ambulance" autoCapitalize="none"/><Text style={s.label}>Password</Text><TextInput style={s.input} value={pass} onChangeText={setPass} placeholder="Password" secureTextEntry/><Text>{error}</Text><TouchableOpacity style={s.btn} onPress={login}><Text style={s.btnText}>Sign in</Text></TouchableOpacity><Text style={s.hint}>Demo: ambulance / ambulance123</Text></View></SafeAreaView>
}
const s=StyleSheet.create({shell:{flex:1,justifyContent:'center',padding:24,backgroundColor:'#f5f7fb'},card:{backgroundColor:'#fff',padding:26,borderRadius:20},logo:{fontSize:26,fontWeight:'800',marginBottom:14},title:{fontSize:28,fontWeight:'800'},sub:{color:'#64748b',marginBottom:22},label:{fontSize:12,fontWeight:'700',marginTop:12},input:{borderWidth:1,borderColor:'#d7dde7',borderRadius:10,padding:12,marginTop:6},btn:{backgroundColor:'#111827',padding:14,borderRadius:10,marginTop:18,alignItems:'center'},btnText:{color:'#fff',fontWeight:'800'},hint:{color:'#64748b',fontSize:12,marginTop:14},ok:{color:'#15803d',fontWeight:'700',marginTop:8},body:{color:'#475569',marginTop:14,lineHeight:21}});
