import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapContainer,TileLayer,Marker,Popup,Polyline,useMap} from 'react-leaflet';
import L from 'leaflet';
import {Activity,Ambulance,AlertTriangle,ArrowRight,Bed,Building2,CheckCircle,Clock3,Crosshair,Hospital,LocateFixed,MapPin,Navigation,Phone,RefreshCw,Route,ShieldAlert,Siren,Stethoscope,Users,XCircle,Radio,Search,Settings,Save} from 'lucide-react';
import 'leaflet/dist/leaflet.css';
import './style.css';

const DEMO=[11.0187,76.9558];
const TILE='https://tile.openstreetmap.org/{z}/{x}/{y}.png';
const OVERPASS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];
const ROUTERS=['https://router.project-osrm.org','https://routing.openstreetmap.de/routed-car'];

const DEFAULT_HOSPITAL_PROFILE={name:'',enabled:true,status:'Ready',beds:10,icu:2,staff:'High',load:20,equipment:['Trauma','ICU','Blood Bank'],location:null};

const emergency={id:'EMR-2048',patient:'Unknown male · approx. 32 yrs',condition:'Suspected chest trauma • altered consciousness • heavy bleeding',severity:'Critical',pickup:'Live GPS pickup',ambulance:'AMB-17'};

const icon=(emoji,bg)=>L.divIcon({className:'rq-marker',html:`<div style="background:${bg}">${emoji}</div>`,iconSize:[40,40],iconAnchor:[20,20],popupAnchor:[0,-20]});
const emergencyIcon=icon('🚨','#dc2626'), ambulanceIcon=icon('🚑','#2563eb'), hospitalIcon=icon('🏥','#16a34a'), nearbyIcon=icon('🏥','#64748b');

function haversine(a,b){const R=6371000,p=Math.PI/180,d1=(b[0]-a[0])*p,d2=(b[1]-a[1])*p;const x=Math.sin(d1/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(d2/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
const km=m=>`${(m/1000).toFixed(1)} km`;
const mins=s=>`${Math.max(1,Math.round(s/60))} min`;

async function fetchOverpass(q){let last;for(const endpoint of OVERPASS){try{const r=await fetch(endpoint,{method:'POST',body:q,headers:{'Content-Type':'text/plain;charset=UTF-8','Accept':'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json();}catch(e){last=e;}}throw last||Error('Hospital search unavailable');}
async function discoverHospitals(pos,radius=8000){
 const [lat,lon]=pos;
 const q=`[out:json][timeout:18];(nwr[amenity=hospital](around:${radius},${lat},${lon});nwr[healthcare=hospital](around:${radius},${lat},${lon}););out center tags;`;
 const data=await fetchOverpass(q); const seen=new Set();
 return (data.elements||[]).map((e,i)=>{const p=e.type==='node'?[e.lat,e.lon]:[e.center?.lat,e.center?.lon];if(!p?.[0]||!p?.[1])return null;const name=e.tags?.name||e.tags?.['name:en']||'Unnamed hospital';const key=`${name}|${p[0].toFixed(5)}|${p[1].toFixed(5)}`;if(seen.has(key))return null;seen.add(key);return{id:`osm-${e.type}-${e.id}-${i}`,name,location:p,airDistance:haversine(pos,p),source:'OpenStreetMap',tags:e.tags||{}};}).filter(Boolean).sort((a,b)=>a.airDistance-b.airDistance).slice(0,10);
}
async function roadMatrix(origin,candidates){
 if(!candidates.length)return [];
 const coords=[origin,...candidates.map(x=>x.location)].map(p=>`${p[1]},${p[0]}`).join(';');
 let last;
 for(const base of ROUTERS){try{const url=`${base}/table/v1/driving/${coords}?sources=0&destinations=${candidates.map((_,i)=>i+1).join(';')}&annotations=distance,duration`;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();if(d.code!=='Ok')throw Error(d.message||'No road matrix');const distances=d.distances?.[0]||[],durations=d.durations?.[0]||[];return candidates.map((x,i)=>({...x,roadDistance:distances[i],roadDuration:durations[i]})).filter(x=>Number.isFinite(x.roadDistance)).sort((a,b)=>a.roadDistance-b.roadDistance);}catch(e){last=e;}}
 throw last||Error('Road routing unavailable');
}
async function route(origin,destination){let last;for(const base of ROUTERS){try{const url=`${base}/route/v1/driving/${origin[1]},${origin[0]};${destination[1]},${destination[0]}?overview=full&geometries=geojson&steps=true`;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();if(d.code!=='Ok'||!d.routes?.[0])throw Error(d.message||'No route');const x=d.routes[0];return{geometry:x.geometry.coordinates.map(([lon,lat])=>[lat,lon]),distance:x.distance,duration:x.duration,steps:(x.legs||[]).flatMap(l=>l.steps||[]).map(s=>({distance:s.distance,name:s.name,text:instruction(s.maneuver,s.name)}))};}catch(e){last=e;}}throw last||Error('Routing unavailable');}
function instruction(m,name){const t=m?.type||'continue',mod=m?.modifier||'';if(t==='depart')return name?`Start on ${name}`:'Start route';if(t==='arrive')return 'Arrive at hospital';if(t==='roundabout'||t==='rotary')return name?`Take the roundabout toward ${name}`:'Enter roundabout';if(t==='turn')return name?`Turn ${mod||'ahead'} onto ${name}`:`Turn ${mod||'ahead'}`;if(t==='merge')return name?`Merge ${mod||''} onto ${name}`.replace('  ',' '):'Merge';if(t==='fork')return name?`Keep ${mod||'ahead'} toward ${name}`:`Keep ${mod||'ahead'}`;return name?`Continue ${mod||'straight'} on ${name}`:`Continue ${mod||'straight'}`;}

function triage(){return{severity:'CRITICAL',confidence:96,suspected:'Major trauma / possible thoracic injury',required:['Trauma','ICU','Blood Bank'],reason:'Altered consciousness plus heavy bleeding and chest trauma are high-risk signals requiring immediate definitive care.'};}
function inferredEquipment(h){
 const text=Object.entries(h.tags||{}).map(([k,v])=>`${k} ${v}`).join(' ').toLowerCase();
 const out=[];
 const add=(word,label)=>{if(text.includes(word)&&!out.includes(label))out.push(label)};
 add('trauma','Trauma'); add('intensive','ICU'); add('icu','ICU'); add('critical','ICU'); add('blood','Blood Bank'); add('cardio','Cardiac'); add('heart','Cardiac'); add('cath','Cath Lab'); add('neurol','Neuro'); add('burn','Burns'); add('ortho','Ortho'); add('operating','OT'); add('surgery','OT'); add('ct','CT'); add('emergency','Emergency');
 return out;
}
function enrichHospital(h){
 const equipment=[...new Set([...(h.equipment||[]),...inferredEquipment(h)])];
 return {...h,equipment,status:h.status||'Unknown',beds:Number.isFinite(h.beds)?h.beds:0,icu:Number.isFinite(h.icu)?h.icu:0,staff:h.staff||'Unknown',load:Number.isFinite(h.load)?h.load:50,registered:false};
}
function clinicalScore(h,pos){
 if(h.status==='Unavailable')return 0;
 const req=['Trauma','ICU','Blood Bank']; const cap=req.filter(x=>(h.equipment||[]).includes(x)).length/req.length;
 const capacity=h.status==='Unknown'?0.5:Math.min(1,(Math.max(0,h.icu)/2)*.6+(Math.max(0,h.beds)/4)*.4);
 const ready=h.status==='Ready'?1:h.status==='Limited'?.55:.45;
 const staff=h.staff==='High'?1:h.staff==='Medium'?.7:h.staff==='Unknown'?.5:.4;
 const load=1-(Math.max(0,Math.min(100,h.load))/100); const d=Math.max(0,1-Math.min(1,haversine(pos,h.location)/15000));
 return Math.round((cap*.35+capacity*.15+ready*.15+staff*.1+load*.1+d*.15)*100);
}

function Pill({children,tone=''}){return <span className={`pill ${tone}`}>{children}</span>}
function Header({role,onLogout}){return <header><div><div className="date">2 September 2026</div><h1>ResQFlow <span>Emergency Network</span></h1></div><div className="role"><span>Signed in as</span><button className="on">{role}</button><button className="logoutBtn" onClick={onLogout}>Log out</button></div></header>}
function Sidebar({page,setPage,role}){const items=['Command Center','Live Emergencies','Hospital Network','Ambulance Fleet','Care Pathways','Analytics'];if(role==='Hospital')items.push('Hospital Controls');return <aside><div className="brand"><div className="logo">R</div><div><b>ResQFlow</b><small>Emergency Network</small></div></div>{items.map(x=><button key={x} className={page===x?'active':''} onClick={()=>setPage(x)}><span className="navIcon">{x==='Hospital Controls'?'⚙':x[0]}</span>{x}</button>)}<div className="sideCard"><b><span className="dot"/> Network operational</b><small>Live GPS + road routing</small><small>Nearby-hospital discovery active</small></div></aside>}
function Stat({icon:Icon,label,value,sub}){return <div className="stat"><Icon size={18}/><div><small>{label}</small><b>{value}</b>{sub&&<em>{sub}</em>}</div></div>}
function HospitalList({items,selected,onSelect}){return <section className="panel"><div className="panelTop"><div><Pill tone="red">NEAREST HOSPITAL ENGINE</Pill><h2>Hospitals ranked by actual road distance</h2></div><Pill tone="green">LIVE GPS</Pill></div><p className="muted">Air distance is only a discovery filter. The final order below uses the road network and travel distance returned by the routing engine.</p>{items.length?items.map((h,i)=><button className={`hospital ${selected===h.id?'selected':''}`} key={h.id} onClick={()=>onSelect(h)}><div className="rank">{i+1}</div><div className="hmain"><b>{h.name}</b><span>{h.source} · Nearby OpenStreetMap result</span><div className="tags"><small>Road {km(h.roadDistance)}</small><small>ETA {mins(h.roadDuration)}</small></div></div><div className="hscore"><strong>{i===0?'NEAREST':`${i+1}`}</strong><small>OSM location</small></div></button>):<div className="empty">No hospitals found yet. Allow GPS and retry.</div>}</section>}
function AIBox({position,candidates,onSelect,onSimulate,onReset,referralEvent,disrupted}){const t=triage();const ranked=candidates.map(enrichHospital).map(h=>({...h,aiScore:clinicalScore(h,position)})).sort((a,b)=>b.aiScore-a.aiScore);const best=ranked.find(h=>h.status!=='Unavailable')||ranked[0];return <section className="panel ai"><div className="panelTop"><div><Pill tone="red">AI DECISION SUPPORT</Pill><h2>Clinical fit from nearby hospitals</h2></div><Pill tone="green">{t.confidence}% confidence</Pill></div><div className="aiGrid"><div><small>TRIAGE</small><strong>{t.severity}</strong><span>{t.suspected}</span><p>{t.reason}</p></div><div><small>REQUIRED CAPABILITY</small><div className="aiTags">{t.required.map(x=><span key={x}>✓ {x}</span>)}</div><p>Hospital capability data comes from available OpenStreetMap tags. Hospital controls are prepared for backend synchronization.</p></div></div>{referralEvent&&<div className="referralBanner"><RefreshCw size={16}/><div><b>Dynamic referral triggered</b><span>{referralEvent.from} became {referralEvent.reason} at {referralEvent.time} → auto-rerouted to <b>{referralEvent.to}</b></span></div></div>}{best&&<div className="recommend"><div><small>BEST NEARBY CLINICAL MATCH</small><b>{best.name}</b><span>{best.aiScore}% match · {best.status} · {km(best.roadDistance)} · {mins(best.roadDuration)}</span></div><button className="primary" onClick={()=>onSelect(best)}>Use clinical match</button></div>}<div className="aiRankList">{ranked.map((h,i)=><div key={h.id} className={`aiRow ${h.status==='Unavailable'?'down':''}`}><span className="aiRank">{i+1}</span><span className="aiName">{h.name}</span><span className="aiPct">{h.aiScore}%</span><span className={`aiStatus ${h.status.toLowerCase().replace(' ','-')}`}>{h.status}</span></div>)}</div><div className="simRow"><button onClick={onSimulate} disabled={disrupted||ranked.length<2}><Radio size={15}/> Simulate hospital status change</button>{disrupted&&<button className="ghost" onClick={onReset}>Reset network</button>}</div></section>}

function Fit({points}){const map=useMap();useEffect(()=>{const valid=points.filter(Boolean);if(valid.length>1)map.fitBounds(valid,{padding:[45,45],maxZoom:15});else if(valid.length===1)map.setView(valid[0],15);},[map,JSON.stringify(points)]);return null}
function MapView({origin,patient,destination,nearby,routeData,onSelectNearby,onLocate,loading,error}){return <section className="panel mapPanel"><div className="mapHead"><div><Pill tone="red">LIVE NAVIGATION</Pill><h2>{destination?.name||'Nearest hospital'}</h2><span>{routeData?`${km(routeData.distance)} · ${mins(routeData.duration)} by road`:'Calculating exact road route…'}</span></div><div><button onClick={onLocate}><LocateFixed size={15}/> GPS</button></div></div><div className="mapWrap"><MapContainer center={origin} zoom={14} scrollWheelZoom style={{height:'100%',width:'100%'}}><TileLayer url={TILE} attribution="&copy; OpenStreetMap contributors" maxZoom={19}/><Fit points={[origin,patient,destination?.location]}/>{routeData?.geometry&&<Polyline positions={routeData.geometry} pathOptions={{weight:6,opacity:.9}}/>}<Marker position={patient} icon={emergencyIcon}><Popup><b>🚨 Emergency pickup</b><br/>Live patient location</Popup></Marker><Marker position={origin} icon={ambulanceIcon}><Popup><b>🚑 AMB-17</b><br/>Live ambulance GPS</Popup></Marker>{destination&&<Marker position={destination.location} icon={hospitalIcon}><Popup><b>🏥 {destination.name}</b><br/>Nearby OpenStreetMap hospital<br/>{destination.roadDistance?`Road: ${km(destination.roadDistance)} · ${mins(destination.roadDuration)}`:''}</Popup></Marker>}{nearby.map(h=><Marker key={h.id} position={h.location} icon={nearbyIcon}><Popup><b>🏥 {h.name}</b><br/>{h.roadDistance?`Road: ${km(h.roadDistance)} · ${mins(h.roadDuration)}`:`Air: ${km(h.airDistance)}`}<br/><button className="popupSelect" onClick={()=>onSelectNearby(h)}>Navigate here</button></Popup></Marker>)}</MapContainer><div className="mapBadge"><span className="liveDot"/> GPS + OSM map + road routing</div>{loading&&<div className="mapNotice"><RefreshCw className="spin" size={15}/> Calculating road route…</div>}{error&&<div className="mapError"><AlertTriangle size={15}/> {error}</div>}</div>{routeData?.steps?.length>0&&<div className="guidance"><div className="guidanceTitle"><Pill tone="red">TURN-BY-TURN</Pill><b>Road guidance</b></div>{routeData.steps.slice(0,6).map((s,i)=><div className="step" key={i}><span>{i+1}</span><div><b>{s.text}</b><small>{s.distance<1000?`${Math.round(s.distance)} m`:`${(s.distance/1000).toFixed(1)} km`}</small></div></div>)}</div>}</section>}


function RolePanel({role,nearest,ranked,status}){
  if(role==='Admin') return <section className="panel rolePanel"><div className="panelTop"><div><Pill tone="green">ADMIN COMMAND</Pill><h2>Network overview</h2></div><Pill>{ranked.length} hospitals nearby</Pill></div><div className="roleGrid"><div><small>ACTIVE EMERGENCY</small><b>EMR-2048</b><span>AMB-17 · Critical</span></div><div><small>NEAREST HOSPITAL</small><b>{nearest?.name||'Searching…'}</b><span>{nearest?`${km(nearest.roadDistance)} · ${mins(nearest.roadDuration)}`:'Awaiting route'}</span></div><div><small>NETWORK STATUS</small><b>Operational</b><span>{status||'Live coordination enabled'}</span></div></div></section>;
  if(role==='Hospital') return <section className="panel rolePanel"><div className="panelTop"><div><Pill tone="green">HOSPITAL DASHBOARD</Pill><h2>Incoming emergency coordination</h2></div><Pill tone="green">READY</Pill></div><div className="roleGrid"><div><small>INCOMING</small><b>EMR-2048</b><span>Critical trauma case</span></div><div><small>AMBULANCE</small><b>AMB-17</b><span>Live GPS shared</span></div><div><small>RECOMMENDED DESTINATION</small><b>{nearest?.name||'Pending'}</b><span>{nearest?`ETA ${mins(nearest.roadDuration)}`:'Waiting for route'}</span></div></div></section>;
  return null;
}

function Login({onLogin}){
 const [mode,setMode]=useState('network');
 const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
 const submit=e=>{e.preventDefault();setError('');
   const accounts=mode==='network'
    ? {admin:{user:'admin',pass:'admin123',role:'Admin'},hospital:{user:'hospital',pass:'hospital123',role:'Hospital'}}
    : {ambulance:{user:'ambulance',pass:'ambulance123',role:'Ambulance'}};
   const key=Object.keys(accounts).find(k=>accounts[k].user===username.trim().toLowerCase()&&accounts[k].pass===password);
   if(key) onLogin(accounts[key].role); else setError('Invalid username or password. Use the demo credentials shown below.');
 };
 const isNetwork=mode==='network';
 return <div className="authShell"><div className="authCard">
   <div className="authBrand"><div className="logo">R</div><div><b>ResQFlow</b><small>Secure Emergency Network</small></div></div>
   <h1 className="authTitle">Sign in</h1><p className="authSub">Choose the access portal for your role.</p>
   <div className="loginTabs"><button className={isNetwork?'on':''} onClick={()=>{setMode('network');setUsername('');setPassword('');setError('')}}>Admin / Hospital</button><button className={!isNetwork?'on':''} onClick={()=>{setMode('ambulance');setUsername('');setPassword('');setError('')}}>Ambulance App</button></div>
   <form onSubmit={submit}>
    <div className="authField"><label>Username</label><input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder={isNetwork?'admin or hospital':'ambulance'} required/></div>
    <div className="authField"><label>Password</label><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password" required/></div>
    {error&&<div className="authError">{error}</div>}
    <button className="authSubmit" type="submit">Sign in as {isNetwork?'Admin / Hospital':'Ambulance'}</button>
   </form>
   <div className="authHint"><b>Demo access</b><br/>{isNetwork?<>Admin: <b>admin / admin123</b><br/>Hospital: <b>hospital / hospital123</b></>:<>Ambulance: <b>ambulance / ambulance123</b></>}<br/><span>Prototype authentication only; production credentials will be moved to the backend.</span></div>
 </div></div>
}


function HospitalControls({profile,setProfile,onLocate}){
 const features=['Emergency','Trauma','ICU','Blood Bank','Cardiac','Cath Lab','CT','Neuro','Burns','Ortho','OT'];
 const toggle=f=>setProfile(p=>({...p,equipment:p.equipment.includes(f)?p.equipment.filter(x=>x!==f):[...p.equipment,f]}));
 const save=()=>{localStorage.setItem('resqflow_hospital_profile',JSON.stringify(profile));setProfile({...profile,savedAt:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});};
 return <section className="panel pagePanel"><div className="panelTop"><div><Pill tone="green">HOSPITAL CONTROLS</Pill><h2>Enable hospital for emergency matching</h2></div><Pill tone={profile.enabled?'green':'red'}>{profile.enabled?'ENABLED':'DISABLED'}</Pill></div><p className="muted">Configure what your hospital can accept. These settings are stored locally in this prototype; the backend will make them visible to ambulances and admins in real time.</p><div className="controlGrid"><label className="wideControl"><span><b>Accept emergency referrals</b><small>Allow ResQFlow to consider this hospital for incoming emergencies.</small></span><input type="checkbox" checked={profile.enabled} onChange={e=>setProfile({...profile,enabled:e.target.checked})}/></label><label><span>Hospital name</span><input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} placeholder="Enter hospital name"/></label><label><span>Emergency beds</span><input type="number" min="0" value={profile.beds} onChange={e=>setProfile({...profile,beds:Number(e.target.value)})}/></label><label><span>ICU beds</span><input type="number" min="0" value={profile.icu} onChange={e=>setProfile({...profile,icu:Number(e.target.value)})}/></label><label><span>Current load (%)</span><input type="number" min="0" max="100" value={profile.load} onChange={e=>setProfile({...profile,load:Number(e.target.value)})}/></label><label><span>Staff readiness</span><select value={profile.staff} onChange={e=>setProfile({...profile,staff:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select></label><label><span>Emergency readiness</span><select value={profile.status} onChange={e=>setProfile({...profile,status:e.target.value})}><option>Ready</option><option>Limited</option><option>Unavailable</option></select></label></div><div className="featureBox"><div className="panelTop"><div><small>CAPABILITIES / EQUIPMENT</small><h3>Enable available services</h3></div><Pill>{profile.equipment.length} enabled</Pill></div><div className="featureToggles">{features.map(f=><button type="button" key={f} className={profile.equipment.includes(f)?'featureOn':''} onClick={()=>toggle(f)}><span>{profile.equipment.includes(f)?'✓':'+'}</span>{f}</button>)}</div></div><div className="controlActions"><button onClick={onLocate}><LocateFixed size={15}/> Use current GPS</button><button className="primary" onClick={save}><Save size={15}/> Save hospital settings</button></div>{profile.savedAt&&<div className="saveNotice"><CheckCircle size={15}/> Settings saved at {profile.savedAt}. Backend synchronization will be added next.</div>}</section>}

function PageView({page,nearest,ranked,position,status,referralEvent,overrides,profile,setProfile,onLocate}){
 const unavailable=ranked.filter(h=>h.status==='Unavailable').length; const ready=ranked.filter(h=>h.status==='Ready').length;
 if(page==='Hospital Controls') return <HospitalControls profile={profile} setProfile={setProfile} onLocate={onLocate}/>;
 if(page==='Live Emergencies') return <section className="panel pagePanel"><div className="panelTop"><div><Pill tone="red">LIVE EMERGENCIES</Pill><h2>Active emergency operations</h2></div><Pill tone="red">1 CRITICAL</Pill></div><div className="tableGrid"><div className="tableHead"><span>Emergency</span><span>Patient</span><span>Severity</span><span>Ambulance</span><span>Destination</span></div><div className="tableRow"><b>{emergency.id}</b><span>{emergency.patient}</span><Pill tone="red">{emergency.severity}</Pill><span>{emergency.ambulance}</span><b>{nearest?.name||'Searching…'}</b></div></div><div className="roleGrid"><div><small>CASE STATUS</small><b>Active</b><span>{status||'Live coordination'}</span></div><div><small>PICKUP</small><b>GPS active</b><span>{position[0].toFixed(5)}, {position[1].toFixed(5)}</span></div><div><small>REFERRAL</small><b>{referralEvent?'Triggered':'None'}</b><span>{referralEvent?`${referralEvent.from} → ${referralEvent.to}`:'No referral event'}</span></div></div></section>;
 if(page==='Hospital Network') return <section className="panel pagePanel"><div className="panelTop"><div><Pill tone="green">NEARBY HOSPITAL NETWORK</Pill><h2>Hospitals detected around ambulance</h2></div><Pill>{ranked.length} nearby · {ready} ready · {unavailable} unavailable</Pill></div><p className="muted">No hospitals are hard-coded to Coimbatore. Results come from OpenStreetMap around the ambulance GPS location and are routed by road.</p><div className="networkCards">{ranked.map((h,i)=><div className={`networkCard ${h.status==='Unavailable'?'down':''}`} key={h.id}><div className="cardTitle"><div><b>{i+1}. {h.name}</b><span>{h.source} · {h.roadDistance?`${km(h.roadDistance)} · ${mins(h.roadDuration)}`:'location found'}</span></div><Pill tone={h.status==='Ready'?'green':h.status==='Unavailable'?'red':''}>{h.status||'Unknown'}</Pill></div><div className="miniStats"><span><b>{h.icu||'—'}</b> ICU</span><span><b>{h.beds||'—'}</b> beds</span><span><b>{h.load??'—'}%</b> load</span><span><b>{h.equipment?.length||0}</b> known capabilities</span></div><div className="tags">{(h.equipment||[]).slice(0,6).map(x=><small key={x}>{x}</small>)}</div></div>)}</div></section>;
 if(page==='Ambulance Fleet') return <section className="panel pagePanel"><div className="panelTop"><div><Pill tone="green">AMBULANCE FLEET</Pill><h2>Fleet operations</h2></div><Pill tone="green">1 ONLINE</Pill></div><div className="networkCards"><div className="networkCard"><div className="cardTitle"><div><b>AMB-17</b><span>Emergency response unit</span></div><Pill tone="green">GPS ONLINE</Pill></div><div className="miniStats"><span><b>Critical</b> case</span><span><b>{nearest?.name||'Pending'}</b> destination</span><span><b>{nearest?mins(nearest.roadDuration):'—'}</b> ETA</span><span><b>Live</b> location</span></div><p className="muted">Current position: {position[0].toFixed(5)}, {position[1].toFixed(5)}</p></div></div></section>;
 if(page==='Care Pathways') return <section className="panel pagePanel"><div className="panelTop"><div><Pill tone="red">CARE PATHWAY</Pill><h2>{emergency.id} emergency lifecycle</h2></div><Pill tone="green">ACTIVE</Pill></div><div className="timeline">{['Emergency detected','AI triage completed','Ambulance dispatched','Hospital capability matched','Hospital accepted / destination set','Stabilize and handover'].map((x,i)=><div className={`timelineItem ${i<4?'done':''}`} key={x}><div className="timelineDot">{i<4?'✓':i+1}</div><div><b>{x}</b><span>{i===0?'Live GPS pickup':i===1?'Critical · 96% decision-support confidence':i===2?'AMB-17':i===3?(nearest?.name||'Matching…'):i===4?(status||'Awaiting hospital response'):'Pending arrival'}</span></div></div>)}</div>{referralEvent&&<div className="referralBanner"><RefreshCw size={16}/><div><b>Dynamic referral recorded</b><span>{referralEvent.from} → {referralEvent.to} · {referralEvent.reason} · {referralEvent.time}</span></div></div>}</section>;
 if(page==='Analytics') return <section className="panel pagePanel"><div className="panelTop"><div><Pill tone="green">ANALYTICS</Pill><h2>Nearby emergency network metrics</h2></div><Pill>Live discovery</Pill></div><div className="analyticsGrid"><div className="metric"><small>NEARBY HOSPITALS</small><b>{ranked.length}</b><span>OpenStreetMap</span></div><div className="metric"><small>READY</small><b>{ready}</b><span>Current discovery set</span></div><div className="metric"><small>AMBULANCES ONLINE</small><b>1</b><span>GPS sharing</span></div><div className="metric"><small>REFERRALS</small><b>{referralEvent?'1':'0'}</b><span>{referralEvent?'Latest event recorded':'No referral yet'}</span></div></div><div className="rankSummary"><h3>Clinical ranking</h3>{ranked.map((h,i)=><div className="summaryRow" key={h.id}><span>#{i+1}</span><b>{h.name}</b><span>{clinicalScore(h,position)}% clinical score · {h.roadDistance?km(h.roadDistance):'—'}</span><Pill tone={h.status==='Ready'?'green':h.status==='Unavailable'?'red':''}>{h.status||'Unknown'}</Pill></div>)}</div></section>;
 return null;
}

function CommandCenter({role,position,gps,gpsAccuracy,nearest,ranked,destination,patient,routeData,busy,error,status,referralEvent,candidates,overrides,locate,search,selectHospital,simulateDisruption,resetNetwork,setStatus}){
 const tri=triage();
 return <>
  <section className="hero"><div><Pill tone="red">{role.toUpperCase()} MODE</Pill><h2>{role==='Ambulance'?'Nearest hospital from the ambulance':role==='Hospital'?'Hospital emergency coordination':'Emergency network command center'}</h2><p>ResQFlow uses live GPS → OpenStreetMap hospital discovery → road-network distance/time. The nearest result is not chosen from straight-line distance alone.</p></div><div className="heroActions"><button onClick={locate}><LocateFixed/> Use my GPS</button><button className="primary" onClick={search} disabled={busy}>{busy?<RefreshCw className="spin"/>:<Search/>}{busy?'Searching…':'Find nearest hospital'}</button></div></section>
  <RolePanel role={role} nearest={nearest} ranked={ranked} status={status}/>
  <div className="locationLine"><Crosshair size={15}/><b>Ambulance location:</b><span>{position[0].toFixed(5)}, {position[1].toFixed(5)}</span><Pill tone="green">{gps}{gpsAccuracy?` · accuracy ${Math.round(gpsAccuracy)} m`:''}</Pill></div>
  <div className="stats"><Stat icon={Ambulance} label="Ambulance" value="AMB-17" sub="GPS sharing"/><Stat icon={Hospital} label="Nearest found" value={nearest?km(nearest.roadDistance):'—'} sub={nearest?mins(nearest.roadDuration):'waiting'}/><Stat icon={Building2} label="Hospitals found" value={ranked.length||'—'} sub="OpenStreetMap"/><Stat icon={ShieldAlert} label="Emergency" value={tri.severity} sub={`${tri.confidence}% triage confidence`}/></div>
  <div className="twoCol"><div><MapView origin={position} patient={patient} destination={destination} nearby={ranked.slice(1,6)} routeData={routeData} onSelectNearby={selectHospital} onLocate={locate} loading={busy} error={error}/><HospitalList items={ranked} selected={destination?.id} onSelect={selectHospital}/></div><div><AIBox position={position} candidates={candidates} onSelect={selectHospital} onSimulate={simulateDisruption} onReset={resetNetwork} referralEvent={referralEvent} disrupted={Object.keys(overrides).length>0}/><section className="panel emergency"><div className="panelTop"><div><Pill tone="red">CRITICAL EMERGENCY</Pill><h2>{emergency.id}</h2></div><Pill tone="green">{status||'Live coordination'}</Pill></div><div className="patient"><Siren/><div><b>{emergency.patient}</b><p>{emergency.condition}</p></div></div><div className="routeInfo"><div><MapPin/><small>PICKUP</small><b>Live ambulance GPS</b></div><ArrowRight/><div><Hospital/><small>NEAREST DESTINATION</small><b>{nearest?.name||'Searching…'}</b></div></div><div className="actionRow"><button className="primary" onClick={()=>setStatus(nearest?`Dispatching AMB-17 to ${nearest.name}`:'No destination selected')}><Ambulance/> Dispatch to nearest</button><button><Phone/> Call hospital</button></div></section><section className="panel explain"><h3>Why the nearest result is accurate</h3><div><CheckCircle/> <span>Hospitals are discovered from live OpenStreetMap data around the ambulance.</span></div><div><CheckCircle/> <span>Multiple candidates are checked against the road network.</span></div><div><CheckCircle/> <span>The nearest card is sorted by routed road distance, not map-circle distance.</span></div><div><AlertTriangle/> <span>AI clinical matching is shown separately so “nearest” and “best medical fit” are never confused.</span></div></section></div></div>
 </>;
}

function App({authRole,onLogout}){
 const role=authRole; const [page,setPage]=useState('Command Center');
 const [position,setPosition]=useState([20.5937,78.9629]);const [gps,setGps]=useState('GPS required');const [gpsAccuracy,setGpsAccuracy]=useState(null);const [patient,setPatient]=useState([20.5937,78.9629]);
 const [hospitals,setHospitals]=useState([]);const [ranked,setRanked]=useState([]);const [lastSearchPos,setLastSearchPos]=useState(null);const [selected,setSelected]=useState(null);const [routeData,setRouteData]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [status,setStatus]=useState('');const [hasGps,setHasGps]=useState(false);
 const [overrides,setOverrides]=useState({});const [referralEvent,setReferralEvent]=useState(null);const [profile,setProfile]=useState(()=>{try{return {...DEFAULT_HOSPITAL_PROFILE,...JSON.parse(localStorage.getItem('resqflow_hospital_profile')||'{}')}}catch{return {...DEFAULT_HOSPITAL_PROFILE}}});
 const candidates=useMemo(()=>ranked.map(enrichHospital).map(h=>({...h,...(overrides[h.id]||{})})),[ranked,overrides]);
 const aiRanked=useMemo(()=>candidates.map(h=>({...h,aiScore:clinicalScore(h,position)})).sort((a,b)=>b.aiScore-a.aiScore),[candidates,position]);
 const aiBest=aiRanked.find(h=>h.status!=='Unavailable')||aiRanked[0]; const nearest=ranked[0]; const destination=selected||aiBest||nearest;
 const simulateDisruption=()=>{const current=aiRanked.find(h=>h.status!=='Unavailable');const next=aiRanked.find(h=>h.id!==current?.id&&h.status!=='Unavailable');if(!current||!next)return;const nextOverrides={...overrides,[current.id]:{status:'Unavailable',load:100}};setOverrides(nextOverrides);setSelected(next);const time=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});setReferralEvent({from:current.name,to:next.name,reason:'overloaded and unavailable',time});setStatus(`Dynamic referral: ${current.name} → ${next.name}`);setPage('Command Center');};
 const resetNetwork=()=>{setOverrides({});setReferralEvent(null);setSelected(null);setStatus('Nearby hospital network reset');};
 const locate=()=>{if(!navigator.geolocation){setError('Browser GPS is not supported.');return;}setError('');setGps('Requesting precise GPS…');navigator.geolocation.getCurrentPosition(p=>{const x=[p.coords.latitude,p.coords.longitude];setPosition(x);setPatient(x);setGpsAccuracy(p.coords.accuracy);setGps(`GPS ±${Math.round(p.coords.accuracy)} m`);setHasGps(true);},()=>{setHasGps(false);setGps('GPS permission denied — enable location to detect nearby hospitals');setError('Location permission is required for nearby-hospital discovery.');},{enableHighAccuracy:true,timeout:15000,maximumAge:10000});};
 const search=async()=>{if(!hasGps)return;setBusy(true);setError('');setStatus('Detecting hospitals near the ambulance…');try{let raw=await discoverHospitals(position,8000);if(raw.length<3)raw=await discoverHospitals(position,15000);const road=await roadMatrix(position,raw);const merged=road.map(enrichHospital);setHospitals(merged);setRanked(merged);setSelected(null);setStatus(merged.length?`${merged.length} nearby hospitals detected · nearest: ${merged[0].name}`:'No hospitals found nearby');}catch(e){setError('Nearby hospital detection failed. Check internet/GPS and try again.');setStatus('');}finally{setBusy(false);}};
 useEffect(()=>{locate();},[]);
 useEffect(()=>{if(hasGps&&(!lastSearchPos||haversine(lastSearchPos,position)>500)){setLastSearchPos(position);search();}},[hasGps,Math.round(position[0]*100),Math.round(position[1]*100)]);
 useEffect(()=>{if(!destination?.location)return;let cancel=false;setRouteData(null);route(position,destination.location).then(x=>{if(!cancel)setRouteData(x)}).catch(()=>{if(!cancel)setError('Road route could not be calculated. Press Find nearest again.')});return()=>{cancel=true};},[destination?.id,Math.round(position[0]*1000),Math.round(position[1]*1000)]);
 const selectHospital=h=>{setSelected(h);setPage('Command Center');};
 return <div className="app"><Sidebar page={page} setPage={setPage} role={role}/><main><Header role={role} onLogout={onLogout}/><div className="content">{page==='Command Center'?<CommandCenter role={role} position={position} gps={gps} gpsAccuracy={gpsAccuracy} nearest={nearest} ranked={ranked} destination={destination} patient={patient} routeData={routeData} busy={busy} error={error} status={status} referralEvent={referralEvent} candidates={candidates} overrides={overrides} locate={locate} search={search} selectHospital={selectHospital} simulateDisruption={simulateDisruption} resetNetwork={resetNetwork} setStatus={setStatus}/>:<PageView page={page} nearest={nearest} ranked={candidates} position={position} status={status} referralEvent={referralEvent} overrides={overrides} profile={profile} setProfile={setProfile} onLocate={locate}/>}</div></main></div>;
}

function Root(){const [authRole,setAuthRole]=useState(()=>sessionStorage.getItem('resqflow_role')); const login=r=>{sessionStorage.setItem('resqflow_role',r);setAuthRole(r)}; const logout=()=>{sessionStorage.removeItem('resqflow_role');setAuthRole(null)}; if(!authRole)return <Login onLogin={login}/>; return <App authRole={authRole} onLogout={logout}/>;}

createRoot(document.getElementById('root')).render(<Root/>);
